# Generated by Django 3.0.4 on 2021-03-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210312_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.CharField(default='lorem', max_length=50, verbose_name='actualiza'),
            preserve_default=False,
        ),
    ]
