# Generated by Django 3.0.4 on 2021-03-15 18:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='activo',
        ),
        migrations.AddField(
            model_name='persona',
            name='cv',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
