# Generated by Django 3.0.4 on 2021-03-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20210315_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='cv',
        ),
        migrations.AddField(
            model_name='persona',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='nombre completo'),
        ),
    ]
